### ISSUE TITLE
Request: "Select All" apps option (instead of clicking every app)

### ISSUE THREAD

**Issue by lpstandardrp** [Kaiserdragon2/IconRequest#12]
Hi,
I hope this finds you well! 
Thank you for IconRequest- it saves me a lot of (invaluable) time!!

> Newb(Me) Alert! 
> This is my first time posting on Github. I hope it is helpful, valuable, and/or ("|") sufficient! If I missed anything, please accept my humble apologies– I welcome and appreciate constructive feedback!!

### I need a bulk apk|app "icon extractor" with a "select all" (apk|app) feature.

1. **Is there any "select all" option that I am not seeing?** 
2. **If not, any suggestions on how to extract icons for all apk or apps at once (without having to select every individual app)?**

OS: Android 9
Steps:
- open IconRequest (v.1.9.5)
 - "Request New"
  - "Share" (icon) returns|>:
`No apps selected. Select at least one app. `
  - "Save" (icon) > (saves empty file) 
 - Select one app (a checkmark replaces the app icon) >  "share" and "save" work respectively
 - **_Is there any "Select All" option on this screen?_** 
 -  In other words, 
**_Does each app require a click/select/toggle?_**

### _If more info or explanation is needed_:
What I mean by "Bulk icon extraction" is selecting multiple apks or installed apps, and extracting ALL their icons at once. All other apps I have tried can extract icons from each individual apk or app one-at-a-time; for 100-500 apks/apps, 100-500 finger-presses are required.

### Ideas/Potential Solutions:
One option that might work is using _AutoSmartClicker_ to read the screen and click/toggle/select every apk|app for me so i dint have to.

_SD Maid_ and _App Manager_ both have the capability to extract an icon one at a time; I havent found a way to do multiple apps|apks at once though.

Thanks again, I am quite thrilled because IconRequest simplifies extraxcting many icoms at once. 

My Humblest Regards~ 
:)

**Comment by Kaiserdragon2** [comment]
Thanks for your request. At the moment their is no option to select all apps at once.
I think it would be a nice feature to have and I will Implement it in the near future.

**Comment by Kaiserdragon2** [comment]
This should close this. https://github.com/Kaiserdragon2/IconRequest/releases/tag/v.1.9.6

**Comment by lpstandardrp** [comment]
@Kaiserdragon2  Brilliant!  Thank YOU!  
"Select All" worked perfect. 
I love apps like IconRequest:  Simple.  Intuitive.  Fast.  Smooth as butter.  
Much Respect~
