### ISSUE TITLE
[Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [Kaiserdragon2/IconRequest#17]
I would like this app's icon to appear as themed/monochrome in the launcher.

[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming)

**Comment by Kaiserdragon2** [comment]
I will implement one in the next release
