### ISSUE TITLE
Expanding on existing feature set

### ISSUE THREAD

**Issue by TotallyAvailable** [Kaiserdragon2/IconRequest#19]
While working on https://github.com/Donnnno/Arcticons/issues/1832 I came across
https://play.google.com/store/apps/details?id=com.bhanu.pinshortcutsfree
Apparently used as workaround for getting Icon Packs (partially) working with the stock Pixel launcher. (Probably unsupported launcher in general)

While I haven't and won't use it personally (therefore can't confirm that it actually works) due to the functionality already being there for me...given that Icon request already has the required base functionality, how much work would it actually be to add the shortcut feature for a separate open source alternative. Icon Request + Weather Shortcut -> (Themed) Open Source Shortcut Maker.
Would that actually work in the end ? Is there more I'm not thinking about ?

([(Simple) App Launcher](https://github.com/FossifyOrg/App-Launcher) almost made it there with a different approach. Bringing the previously denied Icon Pack support request back might certainly be something. Obviously gonna wait until things settle.)

Really just a thought. Maybe you thought about it as well at some point and already know the answer.

**Comment by Kaiserdragon2** [comment]
i think it would be a better idea to create a dedicated app for this functionality but it  is not entirely impossible to do 
if you only want shortcuts for activities with no additional data send to these activities there is already an app that can do this https://github.com/butzist/ActivityLauncher you can even set icons from an iconpack but therefore you have to edit the path by hand you can't chose it through a picker.

**Comment by TotallyAvailable** [comment]
Removing the manual part was actually the goal of asking.
Given that all the required information is already there (just showing covered by selected pack instead of uncovered) can apps actually create already custom themed shortcuts for other installed apps that can simply be dragged to the home screen of an unsupported launcher without any questionable workarounds.

It's really about the clean unprivileged (normal user/default device and permissions - scrapped a couple sentences here after drifting off topic) drag & drop type of a solution that could be recommended to the average user that would like just a bit more of a personalized experience without switching to a completely different launcher.
It could even be (ab)used by more advanced users but again that's beyond the actual question.

This probably should've been my initial wording.

**Comment by Kaiserdragon2** [comment]
i think it would be more like a new app then an additional feature for this one while this app gets IconPacks and their icons there is no way to map them to shortcuts of other apps. The only way to make something similar would be this https://play.google.com/store/apps/details?id=com.bhanu.pinshortcutsfree but with custom presets for app  shortcuts with some tight integration of some Iconpacks and the icons would be need too bee manual be mapped for each supported iconpack and shortcut. Seems like an endless hell of work!

**Comment by Kaiserdragon2** [comment]
I think this isn't something that will be covered by this app.
So i will close this issue.
