### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by codenyte** [Kaiserdragon2/IconRequest#20]
A search feature allowing to query the app list by name or package identifier would be very useful.

**Comment by Kaiserdragon2** [comment]
Thats a good idea i will implement it.

**Comment by codenyte** [comment]
Great, thanks 👍🏻

**Comment by Kaiserdragon2** [comment]
Checkout the new [Release](https://github.com/Kaiserdragon2/IconRequest/releases/tag/v2.2.0)

**Comment by codenyte** [comment]
Awesome, I appreciate it
