### ISSUE TITLE
Where to share details?

### ISSUE THREAD

**Issue by saltsoftdrink** [Kaiserdragon2/IconRequest#21]

**Comment by Kaiserdragon2** [comment]
What do you mean?

**Comment by saltsoftdrink** [comment]
> What do you mean?

If I've selected the app and exported the zip what to do

**Comment by Kaiserdragon2** [comment]
This app helps you if you contribute to an open source icon pack like arcticons or you are able to open an issue in one. This app or this repository doesn't do anything with the selected data.
