### ISSUE TITLE
[Feature Request] Add an option to the "Show Differences" page to only show the differences on one side

### ISSUE THREAD

**Issue by warimiya** [Kaiserdragon2/IconRequest#23]
In Compare Icon Packs > Show Differences, currently it lists differences on both sides. I'd like to be able to see only the missing icons on one side.

For example, if I select Arcticons as the first pack and Delta the second, it will show something like this:
![image](https://github.com/user-attachments/assets/90c2c525-4e04-4229-9d3a-6d547c067d77)

I'd like there to be options to include only icons that Delta has but Arcticons doesn't, and vice versa. 

I'd imagiine something like this in the UI:

![image](https://github.com/user-attachments/assets/5112d2b9-90f4-48f3-947c-4b0776b326cd)

**Comment by Kaiserdragon2** [comment]
This seems like a good idea  i will try to implement that.

**Comment by Kaiserdragon2** [comment]
This should do the trick 
https://github.com/Kaiserdragon2/IconRequest/releases/tag/v2.5.2

**Comment by warimiya** [comment]
Awesome! It works pretty nicely!! 😄
![Screenshot_2024-10-14-03-50-45-83_704a3ee4d11cd40f4f103fff0deabaf6.jpg](https://github.com/user-attachments/assets/326d2143-b312-4a42-a35c-029d0e5767b6)

**Comment by Kaiserdragon2** [comment]
Yeah but there is a bug in the compare code and items that are in both a displayed regardless i will try to fix it in the next days.

**Comment by Kaiserdragon2** [comment]
> Yeah but there is a bug in the compare code and items that are in both a displayed regardless i will try to fix it in the next days.

Fixed it https://github.com/Kaiserdragon2/IconRequest/releases/tag/v2.5.3
