### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by IzzySoft** [Kaiserdragon2/IconRequest#25]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical – due to some graphics differing:

```diff
  -rw----     0.0 fat     3020 b-     1003 defN 1981-01-01 01:01:02 317b240f res/b8.xml
- -rw----     0.0 fat     1928 b-     1928 stor 1981-01-01 01:01:02 706ddc6e res/bB.png
+ -rw----     0.0 fat     1935 b-     1935 stor 1981-01-01 01:01:02 6b1d552e res/bB.png
  -rw----     0.0 fat     1408 b-      423 defN 1981-01-01 01:01:02 5331a5aa res/bL.xml
  -rw----     0.0 fat      880 b-      419 defN 1981-01-01 01:01:02 4d9fcf9f res/bT.xml
  -rw----     0.0 fat      244 b-      244 stor 1981-01-01 01:01:02 8e4da209 res/bX.9.png
@@ -898,7 +898,7 @@
  -rw----     0.0 fat      592 b-      311 defN 1981-01-01 01:01:02 5a0433d1 res/wP.xml
  -rw----     0.0 fat      214 b-      214 stor 1981-01-01 01:01:02 6a5cd9b8 res/w_.png
  -rw----     0.0 fat     5915 b-     5915 stor 1981-01-01 01:01:02 772fe434 res/wb.png
- -rw----     0.0 fat     1493 b-     1493 stor 1981-01-01 01:01:02 ed0a219b res/ww.png
+ -rw----     0.0 fat     1497 b-     1497 stor 1981-01-01 01:01:02 d54c0b99 res/ww.png
  -rw----     0.0 fat      212 b-      212 stor 1981-01-01 01:01:02 3bde0e3f res/x3.9.png
```

Are you maybe using [PNG Crush/Crunch](https://f-droid.org/docs/Reproducible_Builds/#png-crushcrunch), or have those [PNGs generated from vector drawables](https://f-droid.org/docs/Reproducible_Builds/#pngs-generated-from-vector-drawables) (links point to possible solutions)?

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Thanks in advance, and looking forward to your reply!

**Comment by Kaiserdragon2** [comment]
I created a new Release that should fix this issue

**Comment by IzzySoft** [comment]
Thanks – but unfortunately not: diff for 2.5.4 looks exactly the same :cry: 

Btw: could you also add the `gradle-wrapper.jar` next to the `gradle-wrapper.properties`?

**Comment by Kaiserdragon2** [comment]
I added the graddle-wrapper.jar and added vectorDrawables.generatedDensities = [] to hopefully resolve the differences.

**Comment by IzzySoft** [comment]
> I added the graddle-wrapper.jar

Thanks! I forgot to check, so this is entirely my fault: `/gradlew` is missing, too (should be executable then), so for now I'll have to try with the manually injected Gradle 8.7 again…

> to hopefully resolve the differences.

Full success with that, congrats!!! This release will have the green shield up :partying_face:

![image](https://github.com/user-attachments/assets/17aaec9a-4b52-4781-817e-1356039084cb)

One more thing:

```
! repo/de.kaiserdragon.iconrequest_27.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

that can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

**Comment by Kaiserdragon2** [comment]
Just created a new release. This should solve the remaining issues.

**Comment by IzzySoft** [comment]
That worked out fine, thanks – and is RB again as well :smiley:
