### ISSUE TITLE
UI and notification bar overlapping

### ISSUE THREAD

**Issue by akp37** [Kaiserdragon2/IconRequest#26]
Since the last update the interface creeps under the notification area making it impossible to select settings, share, and search. 

For what it's worth, I'm on pixel 9 pro and I downloaded the app from the Play Store.

![Screenshot_20241029-094114.png](https://github.com/user-attachments/assets/2799a357-d3c7-49dd-9ddf-c3eaf0dcd0d0)

----------------------------------------------------
version 2.5.3

de.kaiserdragon.iconrequest
versionCode 25

targetSdk 35
minSdk 21

Updated: Oct 29, 2024

**Comment by Kaiserdragon2** [comment]
Can I ask which android version you are on ?

**Comment by akp37** [comment]
My apologies for the oversight. I'm on Android version 15

**Comment by Kaiserdragon2** [comment]
created a new release that should fix the issue

**Comment by akp37** [comment]
Hey, just wanted to thank you for the quick fix. Everything is working as expected.
