### ISSUE TITLE
Spaces in app names

### ISSUE THREAD

**Issue by Donnnno** [Kaiserdragon2/IconRequest#7]
Hi!

Is it possible to get spaces in the appfilter names, just like with the build in icon request function from candybar?

**Comment by Kaiserdragon2** [comment]
Do you mean that the space in the appfilter name is replaced by an underscore like in the image ? 
![Screenshot 2022-02-05 190052](https://user-images.githubusercontent.com/8929967/152653435-f95fa3f2-c4da-4aa1-8bb7-4477ac73839a.png)

**Comment by Donnnno** [comment]
Yes!

**Comment by Donnnno** [comment]
Would be a nice to have, but Idunno how complicated that would be to make

**Comment by Kaiserdragon2** [comment]
Changed this 
![Screenshot 2022-02-05 193335](https://user-images.githubusercontent.com/8929967/152654383-3b5907ea-c99a-4bba-a9a3-6abfb778bb0d.png)
to this
![Screenshot 2022-02-05 193251](https://user-images.githubusercontent.com/8929967/152654391-24299ef3-d2fb-4a48-b201-6ee20d6a384d.png)
Now it works!

**Comment by Donnnno** [comment]
Woah cool!
